### ISSUE TITLE
作者你好，可以支持一下获取mac钉钉聊天数据库吗？

### ISSUE THREAD

**Issue by Shuai-S** [MarkShawn2020/wechat-dbcracker#2]
作者，希望支持一下钉钉的聊天记录获取，非常感谢

如下，是我找到的参考资料：
[原创]钉钉PC版数据库解密算法分析 https://bbs.kanxue.com/thread-255356.htm
逆向开发学习手机取证之钉钉取证分析 https://blog.csdn.net/qq_35350654/article/details/110663011

**Comment by MarkShawn2020** [comment]
暂时没有时间和兴趣哈~
